name: Test

on:
  push:

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-22.04
    container: wpilib/ubuntu-base:22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run Tests
        run: ./gradlew test
